### ISSUE TITLE
Research into Largo Recent Posts widget and Read Next issues

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-mstoday#64]
Please review the items below and spend up to 2 hrs to determine what might be causing the issues/how to resolve the requests and documenting a response for MS Today. Thanks!

1. 
We’re having trouble with the Largo Recent Posts widget
— It’s not allowing us to program it to show posts in specific story
categories as we’ve done before (see this page for example
<https://mississippitoday.org/flooding/>;). The only way we can get it to
work is to limit to both author and category.
— In most cases (like this page
<https://mississippitoday.org/the-informher/>;), it’s not showing posts in
chronological order.

2. 
We want to put our Read Next widget, which currently appears in our
Article Bottom widget area, in our Donate Interstitial widget area so it
appears higher up in our stories. We tested it in staging (see story
example here http://mstoday.staging.wpengine.com/2020/02/02/retired-state-employees-could-increase-limited-field-of-legislative-candidates-nearly-45-of-seats-unopposed-in-2019),
but we want the ability to customize the appearance. We just want the photo
and headline to appear (no excerpt), but the width also needs adjusting.
You’ll notice the widget area is full-width, which makes the social share
buttons on the left cover the image. It would be good if we could keep the
photo and text inside the widget area the same width as the story. 

2.a. 
We’d also like to bring more attention to the “Read Next” title in the Largo
Related Posts widget. Could we make it orange and bigger just in that
widget area? Is any of this something I can do? If so, where can I go to
play with those styles in staging?

**Comment by joshdarby** [comment]
> We’re having trouble with the Largo Recent Posts widget
— It’s not allowing us to program it to show posts in specific story
categories as we’ve done before (see this page for example
https://mississippitoday.org/flooding/;). The only way we can get it to
work is to limit to both author and category.
— In most cases (like this page
https://mississippitoday.org/the-informher/;), it’s not showing posts in
chronological order.

Quick note that they're attempting to use the widget inside of SiteOrigin WYSIWYG builder

**Comment by joshdarby** [comment]
When they say the widget is not allowing them to not choose a specific category without an author, what's happening? Is it showing an error? Not working at all? Not saving correctly?

**Comment by joshdarby** [comment]
> — In most cases (like this page
https://mississippitoday.org/the-informher/;), it’s not showing posts in
chronological order.

That's might be because instead of using 1 LRP widget that spans the entire row, they're breaking it up like so?

![Screen Shot 2020-02-24 at 4 06 37 PM](https://user-images.githubusercontent.com/18353636/75191182-d9ecd100-571f-11ea-9fea-aeac8cd46bd5.png)

**Comment by joshdarby** [comment]
> We tested it in staging (see story
example here http://mstoday.staging.wpengine.com/2020/02/02/retired-state-employees-could-increase-limited-field-of-legislative-candidates-nearly-45-of-seats-unopposed-in-2019),

I think this was removed? I don't see it on that page

**Comment by joshdarby** [comment]
> We want to put our Read Next widget

Are they referring to Largo Recent Posts, Largo Related Posts, or other?

**Comment by joshdarby** [comment]
In regards to the first issue, I've updated my local db to match their production one.

Dumping the `$shown_ids` var on each rendering of LRP shows something interesting.

First LRP on page:
```
Array
(
    [post__not_in] => Array
        (
            [0] => 
        )

    [posts_per_page] => 1
    [post_status] => publish
    [cat] => 49874
)
```

Second:
```
Array
(
    [post__not_in] => Array
        (
            [0] => 542455
            [1] => 540306
            [2] => 540074
            [3] => 543172
            [4] => 336184
            [5] => 334308
            [6] => 336229
            [7] => 542455
            [8] => 513649
            [9] => 508078
            [10] => 507213
            [11] => 336184
            [12] => 334308
            [13] => 336229
            [14] => 334029
            [15] => 542455
            [16] => 511878
            [17] => 476399
            [18] => 336184
            [19] => 334308
            [20] => 336229
            [21] => 542455
            [22] => 476398
            [23] => 488241
            [24] => 336184
            [25] => 334308
            [26] => 336229
            [27] => 542455
            [28] => 485850
            [29] => 459336
            [30] => 336184
            [31] => 334308
            [32] => 336229
            [33] => 542455
        )

    [posts_per_page] => 1
    [post_status] => publish
    [cat] => 38041
)
```

And each following one is one index higher than the last, including the previous posts shown in the previous LRP widgets, which makes sense.

What doesn't make sense is why it's jumping from 
```
[post__not_in] => Array
        (
            [0] => 
        )
```

to

```
[post__not_in] => Array
        (
            [0] => 542455
            [1] => 540306
            [2] => 540074
            [3] => 543172
            [4] => 336184
            [5] => 334308
            [6] => 336229
            [7] => 542455
            [8] => 513649
            [9] => 508078
            [10] => 507213
            [11] => 336184
            [12] => 334308
            [13] => 336229
            [14] => 334029
            [15] => 542455
            [16] => 511878
            [17] => 476399
            [18] => 336184
            [19] => 334308
            [20] => 336229
            [21] => 542455
            [22] => 476398
            [23] => 488241
            [24] => 336184
            [25] => 334308
            [26] => 336229
            [27] => 542455
            [28] => 485850
            [29] => 459336
            [30] => 336184
            [31] => 334308
            [32] => 336229
            [33] => 542455
        )
```

**Comment by joshdarby** [comment]
So, this page is configured with 4 LRP widgets with these categories, in this order:
Pearl River Flooding
Photo Galleries
Photo Essays
Pearl River Flooding

Each category has this many posts:
Pearl River Flooding: 4
Photo Galleries: 17
Photo Essays: 11

Add that up and you get 32. 

There are 34 posts in the second `$shown_ids` array, but 2 are the same post ID of the post from the first LRP widget, 542455, index 0 and 33. 

So that leaves 32 unique ID's, which is the number of posts combined from those 4 categories 🤔 

So... it looks like LRP is not getting `$shown_ids` correctly and independently, but rather mashing them all together?

**Comment by joshdarby** [comment]
> We want to put our Read Next widget, which currently appears in our
Article Bottom widget area, in our Donate Interstitial widget area so it
appears higher up in our stories. We tested it in staging (see story
example here http://mstoday.staging.wpengine.com/2020/02/02/retired-state-employees-could-increase-limited-field-of-legislative-candidates-nearly-45-of-seats-unopposed-in-2019),
but we want the ability to customize the appearance. We just want the photo
and headline to appear (no excerpt), but the width also needs adjusting.
You’ll notice the widget area is full-width, which makes the social share
buttons on the left cover the image. It would be good if we could keep the
photo and text inside the widget area the same width as the story.

There's no way to target only Donate Interstitials that contain the read next widget, which would be required in order to adjust the width. We'd need to adjust the width for the widget area in general.

In order to hide the Read Next excerpt, they could add something like this to their css, or we could:

```
.scaip .widget.largo-related-posts p {
    display: none;
}
```

>2.a.
We’d also like to bring more attention to the “Read Next” title in the Largo
Related Posts widget. Could we make it orange and bigger just in that
widget area? Is any of this something I can do? If so, where can I go to
play with those styles in staging?

They can also do this by adding something like this to their css, or again, we could do it:
```
.scaip .largo-related-posts .adtitle {
    color: orange;
    font-size: 40px;
}
```
