### ISSUE TITLE
Mobile speed issue assessment

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#92]
Please list any recommendations with estimates for increasing mobile page speed scores

**Comment by benlk** [comment]
See the "High Priority" items in https://github.com/INN/umbrella-mstoday/issues/86#issuecomment-657944923

**Comment by MirandaEcho** [comment]
@benlk - #86 addresses the homepage. Are there other recommendations we can make for articles pages on mobile?

**Comment by benlk** [comment]
Resolving the plugin issues identified by Josh in https://github.com/INN/umbrella-mstoday/issues/85#issuecomment-644263997 will be a major source of improvement.

I'll look for more things, though.

**Comment by benlk** [comment]
Using https://mississippitoday.org/2020/07/14/crews-move-confederate-monument-at-university-of-mississippi-after-years-of-student-activism/ as an example:

- I am not an art director, but does the article need a 16-image slideshow with many functionally-identical images?
- slideshow is using full-size images when they need only be the 771-px-wide version — might be a training question rather than a code fix; depends a lot on how they're assembling slideshows. If they could walk us through how they made that gallery, that would be nice.
- datatables and pdfmake are causing approximately 10 seconds of loading slowness — will be resolved in #85
